### ISSUE TITLE
nobody2018 - _finalizeWithParticipants may revert due to underflow

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-11-covalent-judging#48]
nobody2018

medium

# _finalizeWithParticipants may revert due to underflow

## Summary

In [[_finalizeWithParticipants](https://github.com/sherlock-audit/2023-11-covalent/blob/main/cqt-staking/contracts/BlockSpecimenProofChain.sol#L441)](https://github.com/sherlock-audit/2023-11-covalent/blob/main/cqt-staking/contracts/BlockSpecimenProofChain.sol#L441), there is a for loop that calculates the value of `validatorBitMap`. If there is a participant with an ID greater than 255 in the `participants` array, [[underflow will occur](https://github.com/sherlock-audit/2023-11-covalent/blob/main/cqt-staking/contracts/BlockSpecimenProofChain.sol#L452C39-L452C70)](https://github.com/sherlock-audit/2023-11-covalent/blob/main/cqt-staking/contracts/BlockSpecimenProofChain.sol#L452C39-L452C70). This causes `finalizeSpecimenSession` to be unable to be executed successfully.

## Vulnerability Detail

```solidity
File: cqt-staking\contracts\BlockSpecimenProofChain.sol
441:     function _finalizeWithParticipants(BlockSpecimenSession storage session, uint64 chainId, uint64 blockHeight, bytes32 agreedBlockHash, bytes32 agreedSpecimenHash) internal {
......
447:         mapping(address => SessionParticipantData) storage participantsData = session.participantsData;
448: 
449:         for (uint256 i = 0; i < len; i++) {
450:             participant = participants[i];
451:             SessionParticipantData storage pd = participantsData[participant];
452:->           validatorBitMap |= (1 << (255 - validatorIDs[participant]));
453:             // release gas if possible
454:             if (pd.submissionCounter == 1) {
455:                 pd.submissionCounter = 0;
456:                 pd.stake = 0;
457:             }
458:         }
......
463:     }
```

L452, if `validatorIDs[participant]` is a number greater than 255, then `255 - validatorIDs[participant]` will underflow.

From the definition of some functions below:

- [[function disableValidator(uint128 validatorId) external onlyStakingManager](https://github.com/sherlock-audit/2023-11-covalent/blob/main/cqt-staking/contracts/BlockSpecimenProofChain.sol#L146)](https://github.com/sherlock-audit/2023-11-covalent/blob/main/cqt-staking/contracts/BlockSpecimenProofChain.sol#L146)
- [[function enableValidator(uint128 validatorId) external onlyStakingManager](https://github.com/sherlock-audit/2023-11-covalent/blob/main/cqt-staking/contracts/BlockSpecimenProofChain.sol#L156)](https://github.com/sherlock-audit/2023-11-covalent/blob/main/cqt-staking/contracts/BlockSpecimenProofChain.sol#L156)
- [[function addBSPOperator(address operator, uint128 validatorId) external onlyGovernor](https://github.com/sherlock-audit/2023-11-covalent/blob/main/cqt-staking/contracts/BlockSpecimenProofChain.sol#L176)](https://github.com/sherlock-audit/2023-11-covalent/blob/main/cqt-staking/contracts/BlockSpecimenProofChain.sol#L176)
- [[function disableValidator(uint128 validatorId) external onlyStakingManagerOrOwner](https://github.com/sherlock-audit/2023-11-covalent/blob/main/cqt-staking/contracts/OperationalStaking.sol#L324)](https://github.com/sherlock-audit/2023-11-covalent/blob/main/cqt-staking/contracts/OperationalStaking.sol#L324)
- [[function enableValidator(uint128 validatorId) external onlyStakingManagerOrOwner](https://github.com/sherlock-audit/2023-11-covalent/blob/main/cqt-staking/contracts/OperationalStaking.sol#L333)](https://github.com/sherlock-audit/2023-11-covalent/blob/main/cqt-staking/contracts/OperationalStaking.sol#L333)
- [[function setValidatorCommissionRate(uint128 validatorId, uint128 amount) external onlyOwner](https://github.com/sherlock-audit/2023-11-covalent/blob/main/cqt-staking/contracts/OperationalStaking.sol#L362)](https://github.com/sherlock-audit/2023-11-covalent/blob/main/cqt-staking/contracts/OperationalStaking.sol#L362)

ValidatorID is `uint128`. From [[here](https://github.com/sherlock-audit/2023-11-covalent/blob/main/cqt-staking/contracts/OperationalStaking.sol#L245)](https://github.com/sherlock-audit/2023-11-covalent/blob/main/cqt-staking/contracts/OperationalStaking.sol#L245) it can be inferred that the ID is determined by `validatorsN` and is [[incremented](https://github.com/sherlock-audit/2023-11-covalent/blob/main/cqt-staking/contracts/OperationalStaking.sol#L253)](https://github.com/sherlock-audit/2023-11-covalent/blob/main/cqt-staking/contracts/OperationalStaking.sol#L253).

When the demand of protocol changes, the number of validator is greater than 255, the ID of the new validator will be greater than 255.  
If a Block Specimen Producer with a validatorID greater than 255 submits block specimen proofs via [[submitBlockSpecimenProof](https://github.com/sherlock-audit/2023-11-covalent/blob/main/cqt-staking/contracts/BlockSpecimenProofChain.sol#L328)](https://github.com/sherlock-audit/2023-11-covalent/blob/main/cqt-staking/contracts/BlockSpecimenProofChain.sol#L328), it will not be finalized due to this underflow issue.

## Impact

If the above case occurs, `finalizeSpecimenSession` will not be called successfully. Core functionality is broken.

## Code Snippet

https://github.com/sherlock-audit/2023-11-covalent/blob/main/cqt-staking/contracts/BlockSpecimenProofChain.sol#L452

## Tool used

Manual Review

## Recommendation

Add a check within `submitBlockSpecimenProof`: `validatorIDs[msg.sender]` cannot be greater than 255.

Duplicate of #81

**Comment by sudeepdino008** [comment]
Hi, Covalent network is a permissioned system. It is accepted within the team that the expected number of validators is less than 20. If we want to support more than 255 validators; there's a bunch of system parts that would need overhaul, this being one of them.
