### ISSUE TITLE
cergyk - OperationalStaking::rewardValidators Rewards distribution can be sandwiched to extract most of the rewards from honest validators

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-11-covalent-judging#74]
cergyk

high

# OperationalStaking::rewardValidators Rewards distribution can be sandwiched to extract most of the rewards from honest validators

## Summary
Covalent staking contract allows users which are not validators to partake in the rewards generated by a validator. This is called delegating staked tokens to the validator. Rewards are distributed only when the function `rewardValidators` is called by the staking managers. This enables malicious users to delegate to validators right before distribution of rewards, and withdraw the rewards and stake as a backrun, thus taking a good chunk of the honest validator rewards.

## Vulnerability Detail
We can see that the function `rewardValidators` dir## Summary

## Tool used

Manual Review

## Recommendation
ectly increases the exchangeRate used to evaluate minting price for shares when staking:

https://github.com/sherlock-audit/2023-11-covalent/blob/main/cqt-staking/contracts/OperationalStaking.sol#L308

https://github.com/sherlock-audit/2023-11-covalent/blob/main/cqt-staking/contracts/OperationalStaking.sol#L425

Since this exchangeRate is increased right after the call to `rewardValidators`, the malicious user has access to a part of the rewards distributed to the validator as implemented here:

https://github.com/sherlock-audit/2023-11-covalent/blob/main/cqt-staking/contracts/OperationalStaking.sol#L597-L603

The chunk of the rewards the attacker can extract risklessly this way can be as big as 95%, since the `maxDelegationCap` can be expected to be as big as 20x.

### Scenario
Alice is an honest validator of `validatorId: 1` staking 35000 CQT

Bob is a malicious user having 35000*19 CQT.

Bob sees the owner calls on `rewardValidators`, and does the following:
- front-runs the transaction by delegating all of his tokens to Alice
- back-runs the transaction by unstaking all of his stake

> Note: Bob cannot `transferUnstakedOut` just yet since there is a cooldown of `28 days`. But since `transferUnstakedOut` can be called even if the validator associated with unstaked is `frozen`, the manipulation above still removes all of the risk associated with staking, and Bob gets riskless rewards.

## Impact
A malicious user can steal up to 95% of an honest validator rewards by sandwiching reward distribution

## Tool used

Manual Review

## Recommendation
Please consider adding the following condition to `transferUnstakedOut`:
```diff
+ require(!v.frozen, 'Validator is frozen');
```  

Duplicate of #47

**Comment by sudeepdino008** [comment]
same/similar as https://github.com/sherlock-audit/2023-11-covalent-judging/issues/47
